<Project>
	<PropertyGroup>
		<Version>2.1.5</Version>	
		<Nullable>enable</Nullable>
		<TargetFramework>net7.0</TargetFramework>
		<IsWebConfigTransformDisabled>true</IsWebConfigTransformDisabled> 		
		<Description>github加速神器</Description>
		<Copyright>https://github.com/dotnetcore/FastGithub</Copyright>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>	
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

	<!-- CI环境编译.NET Framework项目（FastGithub.UI为net45）所需的引用程序集 -->
	<ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
	</ItemGroup>
</Project>
